name = "wespa-proxy"
main = "functions/proxy.ts"
compatibility_date = "2024-01-01"

# Environment variables for development
[vars]
# These will be overridden by secrets in production

[env.production]
route = "wespa-ytd.xword.club/api/*"

# For local development, you can set these in .dev.vars file:
# SUPABASE_URL=your_supabase_url
# SUPABASE_ANON_KEY=your_supabase_anon_key